Define `elector`.
veres-one/veres-one-context pull request #5
Opened 2018-10-16 19:46 UTC by mattcollier

2018-10-16 23:34 UTC, dmitrizagidulin approved these changes
👍

2018-10-17 00:53 UTC, gannan08 approved these changes
LGTM

2018-10-17 03:34 UTC, dlongley requested changes

2018-10-17 03:34 UTC, dlongley commented on contexts/veres-one-v1.jsonld
> +    "elector": "wl:elector",
Should have `"@type": "@id"` just like the web ledger context, right?

2018-10-17 14:40 UTC, mattcollier commented
@dlongley ready for another pass.

2018-10-17 14:51 UTC, dlongley approved these changes

2018-10-17 14:52 UTC, merged